### ISSUE TITLE
correct methods

### ISSUE THREAD

**Issue by shuforov** [st3p/imageboard-forum#1]
Переглнь в усіх ентіті щоб методи були приватні.

https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/entities/board_entity.rb#L10

https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/entities/post_entity.rb#L5

**Comment by shuforov** [comment]
І методи повинні йти після expose

**Comment by st3p** [comment]
Виправлено
