### ISSUE TITLE
Correct errors

### ISSUE THREAD

**Issue by shuforov** [st3p/imageboard-forum#2]
Так краще не робити, коли ти визваєш помилку що рекорд не найдено, це будеш бачити тільки ти, а фронтенд побаче 500 і все. Коли рекорд не найдено це не критична помилка і її краще виділяти якимось статус кодом 400 або 422 і відавати кастомну помилку фронтенду що такого рекорда не існує.

https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/admin.rb#L70

**Comment by shuforov** [comment]
наприклад
error!('401 Unauthorized', 401) unless current_user

https://github.com/ruby-grape/grape

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/admin.rb#L13

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/admin.rb#L32

**Comment by st3p** [comment]
Виправив
