### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by shuforov** [st3p/imageboard-forum#4]
Усі коменти які не стосуються ТУДУ прибрати

https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/invites.rb#L6

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/helpers/authentication_helper.rb#L19

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/helpers/authentication_helper.rb#L49

**Comment by st3p** [comment]
Виправив
