### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by shuforov** [st3p/imageboard-forum#5]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/posts.rb#L24

зроби поменше цю строку, винеси в окрему змінну пошук рекорду і використай цю змінну до презентування ентіті.

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/reports.rb#L11

Такого виду переноси краще не робити, зроби так само як я написав коментов вище, винеси в окрему змінну і її визвий.

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/v1/users.rb#L37

Зроби все однією строкою, що можливо повинось в змінні, таке дуже важко читати.

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/8f616a390736f457fc30941c574e22240082af77/app/api/imageboard_api/helpers/authentication_helper.rb#L28

Теж саме, зроби рефакторінг

**Comment by st3p** [comment]
Виправив

**Comment by shuforov** [comment]
https://github.com/st3p/imageboard-forum/blob/0c2d4222cf580c5d27b3c9cd842bda138b8ed367/app/api/imageboard_api/helpers/authentication_helper.rb#L23

тут ще треба зарефакторить, уникай такого виду переносів.

**Comment by st3p** [comment]
переробив

**Comment by shuforov** [comment]
Я мабудь рошки не зрозуміло обяснив, дивись розбий усе по змінним і потім їх визови до JWT
var1 = Rails.application.secrets.secret_key_base
algoritm = algorithm: 'HS256'
.....
decodet_data = JWT.decode(var1, ... algoritm)
decodet_data.&first&.with_indifferent_access
Розумієш про що я?
Так читабельність коду одразу зручнішою стає, я розумію що тобі все зроззуміло і в принцепі ти знаєш що де відбувається, але пройде декілька неділь і місяців ти загляниш сюди і будеш сидіти минут 15 думати що я тут взагалі хотів зробити :)
Перероби щоб гарненько було.

**Comment by st3p** [comment]
Виніс сам токен і секрет. Можна ще винести true і 'HS256', але не думаю, що це буде гарно виглядати

**Comment by shuforov** [comment]
Забув ось це переробити, перечитай комент вище.
                          &.first
                          &.with_indifferent_access

**Comment by st3p** [comment]
Переробив
